
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA COMMENT CONSTANT GLOBL INSTR LABEL LABELREF LPAREN PREGEN REGISTER RPAREN START STRINGprogram : STARTprogram : program COMMENTpre : PREGEN\n           | PREGEN STRING\n           | PREGEN CONSTANT\n           | PREGEN LABELREF\n           | GLOBLarg : CONSTANTarg : REGISTERarg : LPAREN REGISTER RPARENarg : LABELREFarg : CONSTANT LPAREN arg RPARENline : INSTR arg COMMA arg COMMA arg\n            | INSTR arg COMMA arg\n            | INSTR arg\n            | INSTRprogram : program lineprogram : program LABELprogram : program pre'
    
_lr_action_items = {'START':([0,],[2,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,21,23,25,26,],[0,-1,-2,-17,-18,-19,-16,-3,-7,-15,-8,-9,-11,-4,-5,-6,-14,-10,-12,-13,]),'COMMENT':([1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,21,23,25,26,],[3,-1,-2,-17,-18,-19,-16,-3,-7,-15,-8,-9,-11,-4,-5,-6,-14,-10,-12,-13,]),'LABEL':([1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,21,23,25,26,],[5,-1,-2,-17,-18,-19,-16,-3,-7,-15,-8,-9,-11,-4,-5,-6,-14,-10,-12,-13,]),'INSTR':([1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,21,23,25,26,],[7,-1,-2,-17,-18,-19,-16,-3,-7,-15,-8,-9,-11,-4,-5,-6,-14,-10,-12,-13,]),'PREGEN':([1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,21,23,25,26,],[8,-1,-2,-17,-18,-19,-16,-3,-7,-15,-8,-9,-11,-4,-5,-6,-14,-10,-12,-13,]),'GLOBL':([1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,21,23,25,26,],[9,-1,-2,-17,-18,-19,-16,-3,-7,-15,-8,-9,-11,-4,-5,-6,-14,-10,-12,-13,]),'CONSTANT':([7,8,18,19,24,],[11,16,11,11,11,]),'REGISTER':([7,13,18,19,24,],[12,20,12,12,12,]),'LPAREN':([7,11,18,19,24,],[13,19,13,13,13,]),'LABELREF':([7,8,18,19,24,],[14,17,14,14,14,]),'STRING':([8,],[15,]),'COMMA':([10,11,12,14,21,23,25,],[18,-8,-9,-11,24,-10,-12,]),'RPAREN':([11,12,14,20,22,23,25,],[-8,-9,-11,23,25,-10,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'line':([1,],[4,]),'pre':([1,],[6,]),'arg':([7,18,19,24,],[10,21,22,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> START','program',1,'p_startprogram','parsemips.py',100),
  ('program -> program COMMENT','program',2,'p_addcomment','parsemips.py',105),
  ('pre -> PREGEN','pre',1,'p_pre','parsemips.py',109),
  ('pre -> PREGEN STRING','pre',2,'p_pre','parsemips.py',110),
  ('pre -> PREGEN CONSTANT','pre',2,'p_pre','parsemips.py',111),
  ('pre -> PREGEN LABELREF','pre',2,'p_pre','parsemips.py',112),
  ('pre -> GLOBL','pre',1,'p_pre','parsemips.py',113),
  ('arg -> CONSTANT','arg',1,'p_constarg','parsemips.py',118),
  ('arg -> REGISTER','arg',1,'p_regarg','parsemips.py',123),
  ('arg -> LPAREN REGISTER RPAREN','arg',3,'p_parentregarg','parsemips.py',128),
  ('arg -> LABELREF','arg',1,'p_labelarg','parsemips.py',133),
  ('arg -> CONSTANT LPAREN arg RPAREN','arg',4,'p_offsetarg','parsemips.py',138),
  ('line -> INSTR arg COMMA arg COMMA arg','line',6,'p_line','parsemips.py',143),
  ('line -> INSTR arg COMMA arg','line',4,'p_line','parsemips.py',144),
  ('line -> INSTR arg','line',2,'p_line','parsemips.py',145),
  ('line -> INSTR','line',1,'p_line','parsemips.py',146),
  ('program -> program line','program',2,'p_addline','parsemips.py',154),
  ('program -> program LABEL','program',2,'p_addlabel','parsemips.py',160),
  ('program -> program pre','program',2,'p_addpre','parsemips.py',166),
]
